### ISSUE TITLE
Polynomial ring over a finite field

### ISSUE THREAD

**Issue by Fiono11** [dimforge/alga#92]
Hello!

I would like to construct a polynomial ring over a finite field, but I am new to Rust and this type of math.
Can this library be used for this and, if so, can someone point me in the right direction?

Thanks!

**Comment by WaDelma** [comment]
[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0cf5fbc181222fd41a3d66ff33999490) is an implementation of polynomial ring. The code is bit gnarly and I didn't have time to implement the multiplication today, but it should give idea on how this crate is supposed to be used.

You can implement [`std::ops::`](https://doc.rust-lang.org/std/ops/index.html) traits to make calling operations cleaner and use [`alga_derive`](https://docs.rs/alga_derive/0.9.1/alga_derive/)  crate to skip the boilerplate of implementing all those traits (and generating [`quickcheck`](https://docs.rs/quickcheck/0.9.0/quickcheck/) tests that check that the algebraic properties actually hold). I would have probably used it myself here, but apparently playpen doesn't have it as possible dependency.

It isn't strictly over finite fields as there isn't trait for that, but that could be potentially arranged (You could create one just for your own project too and you have to implement your own finite fields in any case).

You can also look at [example](https://github.com/rustsim/alga/blob/dev/alga/examples/vectors.rs) to get another look at how the library can be used.

If you have any question, feel free to ask!

**Comment by Fiono11** [comment]
Wow, thank you so much! Will take a look at these and try to understand how they work.
